### ISSUE TITLE
data

### ISSUE THREAD

**Issue by smallmax00** [Yunkun-Zhang/CITE#1]
Very nice work, can you provide 'data/gastric_cls3_ann/train_all_0.2.txt' please?

Thx

**Comment by Yunkun-Zhang** [comment]
The annotation files can be generated by running `python tools/ann.py`
Or they can be downloaded here: [gastric_cls3_ann.zip](https://github.com/Yunkun-Zhang/CITE/files/11907795/gastric_cls3_ann.zip)
