### ISSUE TITLE
ModuleNotFoundError: No module named 'models'

### ISSUE THREAD

**Issue by buihanhtrang** [Yunkun-Zhang/CITE#6]
I ran the code as instructed, but encountered the following error. 
While running this code: "!mim train mmcls /configs/gastric/cite/clip-vitb16_biolinkbert-l_cb_bs128_i1000.py"
Did I make any mistake here? Can you correct it for me?
Thank you a lot for your code.
![image](https://github.com/Yunkun-Zhang/CITE/assets/149102046/6aa4c5a1-c04c-4d02-8558-b3d56c1dbe68)

**Comment by Yunkun-Zhang** [comment]
Be sure the root directory is in the environment variable `PYTHONPATH`. You can run the code by

```bash
PYTHONPATH=.:$PYTHONPATH mim train mmcls <config>
```

**Comment by buihanhtrang** [comment]
I still cant run this code, are u safe the weight of model? Because the old version of mmcv now cant now import Model as the error above. So I need to install mmcv new version but it said that cant not import Config and DicAction...Thank you for your answer.
